project:
  type: website

website:
  announcement: 
    dismissable: false
    content: "**BRINGING BIG DATA & ADVANCED COMPUTATIONAL MODELLING TOGETHER**"
    type: info
    position: above-navbar
  title: "Pandora & IsoMemo Documentation Hub"
  search: true
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: apps.qmd
        text: Applications
      - href: faq.qmd
        text: FAQ
      - href: bugs.qmd
        text: Bug Reports
    tools:
      - icon: github
        href: https://github.com/Pandora-IsoMemo
  page-footer: "Pandora & IsoMemo Comutational Lab"

format:
  html:
    echo: false
    theme:
      - flatly
      - style.scss
    grid:
      body-width: 1280px
    smooth-scroll: true
