project:
  type: website

website:
  announcement: 
    icon: info-circle
    dismissable: false
    content: "**This side is still under construction**"
    type: warning
    position: below-navbar
  title: "Pandora & IsoMemo Documentation Hub"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: apps.qmd
        text: Apps
      - href: faq.qmd
        text: FAQ
      - href: bugs.qmd
        text: Bug Reports
    right:
      - icon: fa-brands fa-github
        href: "https://github.com/Pandora-IsoMemo"

format:
  html:
    echo: false
    theme: cosmos
    #css: templates/2col/assets/css/tailwind/tailwind.min.css
    #css: templates/assets/css/theme.css
    toc: true
