## Installation via docker (recommended)

### 1. Install the software Docker

Download installation files from one of the links below and follow installation
instructions:

* Windows: https://docs.docker.com/desktop/windows/install/
* MacOS: https://docs.docker.com/desktop/install/mac-install/
* Linux: https://docs.docker.com/desktop/install/linux-install/

### 2. Download and install docker image of the app
This image contains all elements necessary for you to run the app from a web
browser. Run this code in a local terminal 

#### 2. a) Open a terminal (command line):
- Windows command line: 
   1. Open the Start menu or press the `Windows key` + `R`; 
   2. Type cmd or cmd.exe in the Run command box;
   3. Press Enter.
- MacOS: open the Terminal app.
- Linux: most Linux systems use the same default keyboard shortcut to start the
  command line: `Ctrl`-`Alt`-`T` or `Super`-`T`

#### 2. b) Copy paste the text below into the terminal and press Enter:

```bash
docker pull ghcr.io/pandora-isomemo/{docker-image}:main
```

### 3. Run the application in Docker 

Steps 1 and 2 install the app. To run the app at any time after the installation
open a terminal (as described in point 2) copy paste the text below into the
terminal and press Enter. Wait for a notification that the app is in “listening”
mode.

```bash
docker run -p 3838:3838 ghcr.io/pandora-isomemo/{docker-image}:main
```

If the app is shutdown on Docker or if the terminal is closed the app will no
longer work in your web browser (see point 4).

### 4. Display the app in a web browser

Once the app is running in Docker you need to display it in a web browser. For
this, copy-paste the address below into your web browser’s address input and
press Enter.

```bash
http://127.0.0.1:3838/
```

### Troubleshooting

1. You may not be able to install Docker due a lack of administrative rights.
   If so, contact your IT department to grant installation rights.
2. While trying to use Docker on Windows you may receive the message that the
   “Windows Subsystem for Linux” is missing. To install it follow these
   [instructions](https://learn.microsoft.com/en-us/windows/wsl/install)
3. While trying to use Docker on Windows you may receive the error “Hardwar 
   assisted virtualization and data execution protection must be enabled in
   the BIOS”. This requires you to access your computer BIOS to enable
   “hardware virtualization”. Mode of access and BIOS menu options vary with
   computer model.
4. In some problematic cases, you may consider using an older version of Docker.
   See: https://docs.docker.com/desktop/release-notes/

## Local Installation

### Install R

- Windows: https://cran.r-project.org/bin/windows/base/
- MacOS: https://cran.r-project.org/bin/macosx/
- Linux (Ubuntu): https://cran.r-project.org/bin/linux/ubuntu/

### Download the app

Open a local R Console and add these two additional Repositories.

```r
options(
  repos = c(
    getOption("repos"),
    PANDORA = "https://Pandora-IsoMemo.github.io/drat/"
    INWTlab = "https://inwtlab.github.io/drat/"
  )
)
```

Load and Install the R-Package

```r
install.packages("{package}")
```

### Start the app

Load and attach package

```r
library("{package}")
```

Run the app

```r
{package}::startApplication()
```
